name: CI

on:
  pull_request:
    branches: [main]

jobs:
  validate-pr-title:
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
      - name: ruff format
        run: uv run --frozen --all-extras ruff format --check --diff
      - name: ruff check
        run: uv run --frozen --all-extras ruff check
      - name: pyright
        run: uv run --frozen --all-extras pyright

  test:
    needs:
      - validate-pr-title
      - check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-llama-cpp
        id: setup-llama-cpp
        with:
          hf-models: |
            unsloth/embeddinggemma-300m-GGUF:Q4_0
            unsloth/Qwen3-4B-Instruct-2507-GGUF:IQ4_NL
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
      - name: pytest
        run: uv run --frozen --all-extras pytest -v
        env:
          LLAMA_OFFLINE: 1
          LLAMA_CACHE: ${{ steps.setup-llama-cpp.outputs.llama-cache }}
